version: '3.3'

services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
            - MYSQL_DATABASE=dbteste
            - MYSQL_USER=usuario
            - MYSQL_PASSWORD=welcome1
            - MYSQL_ROOT_PASSWORD=welcome1
    volumes:
            - ./database/startup:/docker-entrypoint-initdb.d
            - /data2:/var/lib/mysql
  php:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_HOST=db